### ISSUE TITLE
deterministic?

### ISSUE THREAD

**Issue by Fil** [Fil/plot-cli#2]
Plot's stylesheet has a random id. In the test repo we normalize it for reproducibility, by [reindexing](https://github.com/observablehq/plot/blob/8757c028e12ba434ff2f199f8789e338140170fd/test/plot.js#L16) all styles, markers and clip-paths. Maybe we should do it here also?

**Comment by tophtucker** [comment]
Fixed by [0.6.6](https://github.com/observablehq/plot/blob/main/CHANGELOG.md#066), right?
>Plot has a few improvements for server-side rendering. Plot now assumes a high pixel density display when headless. The default class name for plots is now deterministically generated (plot-d6a7b5) rather than randomly generated; this makes it easier to apply overrides to Plot’s default styles with an external stylesheet. (The default class name will change if Plot’s default styles change in a future release.)
